using Pointer.Domain.Enums;

namespace Pointer.Domain.Entity;

public class User : BaseEntity
{
    public Guid PublicId { get; set; } = Guid.NewGuid();
    public string Email { get; set; } = string.Empty;
    public string PasswordHash { get; set; } = string.Empty;
    public string DisplayName { get; set; } = string.Empty;

    /// <summary>
    /// <b>Platform role (DB-11f).</b> Non-null only for super admins (the global is_super_admin
    /// role); NULL for every other identity. Read via Role.IsSuperAdmin / UserMapper.SessionRole.
    /// </summary>
    public int? RoleId { get; set; }

    /// <summary>See <see cref="RoleId"/> — the platform role (DB-11f).</summary>
    public Role? Role { get; set; }

    /// <summary>
    /// Identity-level switch (false only after erase/merge). Per-workspace enable/disable is
    /// <see cref="WorkspaceMembership.IsActive"/>.
    /// </summary>
    public bool IsActive { get; set; } = true;

    public string? Language { get; set; }
    public string? Theme { get; set; }

    /// <summary>
    /// Per-user "add comment" widget keyboard shortcut, e.g. "ctrl+alt+shift+KeyC" — synced to the
    /// account (not per-browser) so it follows the user across machines/browsers. Null = the
    /// widget's built-in default (Ctrl+Alt+Shift+C / Control+Option+Shift+C).
    /// </summary>
    public string? AddCommentShortcut { get; set; }

    /// <summary>
    /// Rotating session/token invalidation stamp (H1/H2). Embedded as the JWT <c>stamp</c> claim and
    /// in reset-token payloads; bumped (new Guid) on password change, disable, and reject so existing
    /// access tokens and outstanding reset links stop validating. Enforcement is gated by
    /// <c>Auth:ValidateSecurityStamp</c> — see AuthenticationExtensions.
    /// </summary>
    public Guid SecurityStamp { get; set; } = Guid.NewGuid();

    public bool IsDemo { get; set; }

    /// <summary>The real human email entered at demo provisioning time. Null for non-demo users. Cleared on upgrade.</summary>
    public string? RecipientEmail { get; set; }

    /// <summary>
    /// This account has no usable password and signs in only via a quick-access magic link.
    /// </summary>
    /// <remarks>
    /// Its PasswordHash is deliberately random and unusable. The flag exists so password login can
    /// refuse the account explicitly rather than relying on the hash never matching — a future
    /// "set your password" path must not silently turn a link-only client into a password account.
    /// </remarks>
    public bool PasswordlessOnly { get; set; }

    /// <summary>
    /// Non-null ⇔ this row was merged into another identity by the DB-11a same-e-mail merge and is
    /// soft-deleted. Points at the canonical row's <see cref="Id"/>.
    /// </summary>
    public int? MergedIntoUserId { get; set; }

    /// <summary>Every workspace this identity has ever joined (live and ended). DB-11a.</summary>
    public ICollection<WorkspaceMembership> Memberships { get; set; } =
        new List<WorkspaceMembership>();

    /// <summary>
    /// Non-null = tombstone (DB-11c): e-mail/name/secrets replaced, memberships ended, <c>DeletedAt</c>
    /// set; <see cref="PublicId"/> is kept so authored content still resolves to "Deleted user".
    /// </summary>
    public DateTime? ErasedAt { get; set; }

    /// <summary>
    /// DB-14. Non-null = the identity proved control of <see cref="Email"/> (verification link,
    /// addressed invite, operator-created, or grandfathered by the DB-14 backfill). Null =
    /// unverified: may read and comment, may not act as an admin (<c>RequireVerifiedEmailFilter</c>).
    /// Reset to null by <c>DemoService.UpgradeAsync</c> (new address) and never by anything else —
    /// DB-11d's confirm step sets it (the new address was just proven).
    /// </summary>
    public DateTime? EmailVerifiedAt { get; set; }

    /// <summary>
    /// R5-61: base32 TOTP secret, AES-256-GCM encrypted via <c>IApiKeyProtector.Encrypt()</c>. Null =
    /// MFA not enrolled (or enrolled-but-unverified — <c>POST /api/me/mfa/enrol</c> writes this
    /// before <see cref="TotpEnabledAt"/> is set; a fresh enrol attempt overwrites it). Only ever
    /// read/written by MFA-specific code paths gated on <c>Role.IsSuperAdmin</c> (§3.4) — the
    /// column exists on every user but is meaningless for non-super-admins.
    /// </summary>
    public string? TotpSecret { get; set; }

    /// <summary>R5-61: set when the TOTP code is verified and MFA becomes enforced at login. Null =
    /// not enabled (either never enrolled, or a secret was generated by enrol but never verified).</summary>
    public DateTime? TotpEnabledAt { get; set; }

    /// <summary>
    /// R5-61 review fix #1 (replay protection, DB-RULES R1 — additive): the RFC 6238 time-step
    /// counter of the last TOTP code that was accepted (enrol-verify, login-complete, or disable).
    /// A code whose step is <c>&lt;= (TotpLastStep ?? -1)</c> is refused even if it is otherwise a
    /// cryptographically valid code for the current ±1 window — this is what stops the exact same
    /// 6-digit code (observed over-the-shoulder, in a proxy log, etc.) from being replayed a second
    /// time inside the same ~30s window it was issued for. Null = no code has ever been accepted yet
    /// (fresh enrol, or after disable clears it — §DB-11-style tombstone semantics: a full disable
    /// resets this so a future re-enrol starts with a clean slate, same as <see cref="TotpSecret"/>).
    /// </summary>
    public long? TotpLastStep { get; set; }
}
